---
title: "Pain Differences Between Sexes - Further Analysis"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    theme:
      bg: "#202123"
      fg: "#B8BCC2"
      primary: "#EA80FC"
      secondary: "#00DAC6"
      base_font:
        google: Prompt
      heading_font:
        google: Proza Libre
---

### Zachary Traylor's Master's Thesis Cont.

```{r setup, include=FALSE}
library(ggpubr)
library(car)
library(lme4)
library(multcomp)
library(tidyverse)
library(rstatix)
library(lmerTest)
library(rcompanion)
library(emmeans)
library(readr)
library(ggplot2)
require(gridExtra)
library(ggsignif)
library(png)
library(reshape2)
library(afex)
options(width = 115)
```

------------------------------------------------------------------------

# Simplified Model (2-way ANOVA, only using Perception trial)

First, we load only the Perception condition's data.
```{r loading data, message=FALSE}
ratings <- read_csv("Perception_ratings.csv", col_types = cols(Sex = col_factor(
                    levels = c("male", "female")),
                    Stim = col_factor(levels = c("low", "med", "high"))))

erp <- read_csv("Perception_erp.csv", col_types = cols(...1 = col_skip(), 
                Sex = col_factor(levels = c("male", "female")), 
                Stimulus = col_factor(levels = c("1", "2", "3"))))

freq <- read_csv("Perception_freq.csv", col_types = cols(...1 = col_skip(), 
                 Sex = col_factor(levels = c("male", "female")), 
                 Stimulus = col_factor(levels = c("1", "2", "3"))))
```

Now we will run the same model as before, but without the Condition factor since condition is fixed

## Verbal Pain Ratings
```{r first anova model, message=FALSE, warning=FALSE}
ratings <- na.omit(ratings)
pain.model <- aov_ez(id = "Subject", 
                     dv = "Pain", 
                     data = ratings, 
                     between = "Sex", 
                     within = "Stim",
                     fun_aggregate = mean)
knitr::kable(nice(pain.model))

post.hoc <- emmeans(pain.model, ~ Stim)  # significant main effect of Stimulus
print(summary(as.glht(pairs(post.hoc)), test=adjusted("bonferroni")))
```

### ANOVA Assumptions

1. Normality
```{r first normality, message=FALSE}
R = residuals(pain.model)
qqPlot(R)
hist(R)
```

2. Homogeneity of Variance
```{r first homogeneity, message=FALSE}
leveneTest(Pain ~ Sex * Stim, data = ratings)
table(ratings$Sex)
table(ratings$Stim)
```

3. Sphericity (already Greenhouse-Geisser corrected)

### Plot our results
```{r verbal pain plot, message=FALSE, warning=FALSE}
afex_plot(pain.model, x = "Stim", trace = "Sex", error = "none", 
          mapping = c("color", "fill"), 
          data_geom = geom_boxplot, data_arg = list(width = 0.7), 
          point_arg = list(size = 1.5), line_arg = list(size = 1),
          dodge = 0.8) +
  ylab("Verbal Pain Ratings") +
  xlab("Stimulus Level") +
  scale_fill_manual(values = c("#2274A5", "#CE7DA5")) + 
  scale_color_manual(values = c("#2274A5", "#CE7DA5"))
```

$~$

------------------------------------------------------------------------

$~$

## Neural Correlates (Amplitudes)
```{r}
model <- function(df, title, post=FALSE, inter=FALSE) {
  temp <- subset(df, df$Component==title)
  #temp <- temp[!(temp$Value %in% boxplot(temp$Value)$out),]  # remove rows with outliers
  
  full.model <- aov_ez(id = "ID", 
                       dv = "Value", 
                       data = temp, 
                       between = "Sex", 
                       within = "Stimulus",
                       fun_aggregate = mean)

  if (post) {  # if we are running post-hoc...
    post.hoc <- emmeans(full.model, ~ Sex)
    print(summary(as.glht(pairs(post.hoc)), test=adjusted("bonferroni")))
  }
  if (inter) {  # if we have an interaction
    post.hoc <- emmeans(full.model, ~ Sex|Stimulus)
    print(summary(as.glht(pairs(post.hoc)), test=adjusted("bonferroni")))
  }
  
  # assumption testing
  print("Sample size:")

  # 1.  Normality
  print("NORMALITY: Visually inspect for non-normal data")
  R = residuals(full.model)
  qqPlot(R)
  hist(R)
  
  # 2.  Homogeneity of Variance (Levene's test)
  print("HOMOGENEITY OF VARIANCE: For Levene's test, p of < 0.05 is a violation, but if there is little to no group imbalance (ex: between male/female) this is acceptable")
  print(leveneTest(Value ~ Sex * Stimulus, data = temp))
  print(table(temp$Sex))
  print(table(temp$Stimulus))

  # 3. Sphericity
  print("Violations of sphericity have been Greenhouse-Geisser corrected")
  
  return(full.model)
}
```

### N1
```{r}
m <- model(erp, "N1_Amp")
knitr::kable(nice(m))
afex_plot(m, x = "Stimulus", trace = "Sex", error = "none", 
          mapping = c("color", "fill"), 
          data_geom = geom_boxplot, data_arg = list(width = 0.7), 
          point_arg = list(size = 1.5), line_arg = list(size = 1),
          dodge = 0.8) +
  ylab("N1 Amplitude (μV)") +
  scale_fill_manual(values = c("#2274A5", "#CE7DA5")) + 
  scale_color_manual(values = c("#2274A5", "#CE7DA5")) +
  scale_x_discrete(name = "Stimulus Level", labels = c("Low", "Med", "High"))
```

### N2
```{r}
m <- model(erp, "N2_Amp")
knitr::kable(nice(m))
afex_plot(m, x = "Stimulus", trace = "Sex", error = "none", 
          mapping = c("color", "fill"), 
          data_geom = geom_boxplot, data_arg = list(width = 0.7), 
          point_arg = list(size = 1.5), line_arg = list(size = 1),
          dodge = 0.8) +
  ylab("N2 Amplitude (μV)") +
  scale_fill_manual(values = c("#2274A5", "#CE7DA5")) + 
  scale_color_manual(values = c("#2274A5", "#CE7DA5")) +
  scale_x_discrete(name = "Stimulus Level", labels = c("Low", "Med", "High"))
```

### P2
```{r}
m <- model(erp, "P2_Amp", inter = TRUE)
knitr::kable(nice(m))
afex_plot(m, x = "Stimulus", trace = "Sex", error = "none", 
          mapping = c("color", "fill"), 
          data_geom = geom_boxplot, data_arg = list(width = 0.7), 
          point_arg = list(size = 1.5), line_arg = list(size = 1),
          dodge = 0.8) +
  ylab("P2 Amplitude (μV)") +
  scale_fill_manual(values = c("#2274A5", "#CE7DA5")) + 
  scale_color_manual(values = c("#2274A5", "#CE7DA5")) +
  scale_x_discrete(name = "Stimulus Level", labels = c("Low", "Med", "High"))
```

### Gamma
```{r}
m <- model(freq, "Gamma_Amp", post = TRUE)
knitr::kable(nice(m))
afex_plot(m, x = "Stimulus", trace = "Sex", error = "none", 
          mapping = c("color", "fill"), 
          data_geom = geom_boxplot, data_arg = list(width = 0.7), 
          point_arg = list(size = 1.5), line_arg = list(size = 1),
          dodge = 0.8) +
  ylab("High-Gamma  Band Amplitude (dB)") +
  scale_fill_manual(values = c("#2274A5", "#CE7DA5")) + 
  scale_color_manual(values = c("#2274A5", "#CE7DA5")) +
  scale_x_discrete(name = "Stimulus Level", labels = c("Low", "Med", "High"))
```
